[34m[1mwandb[39m[22m:   4 of 4 files downloaded.
Traceback (most recent call last):
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/tour_eval_pred/run.py", line 180, in <module>
    go(args)
  File "/home/orestas41/project-FootballPredict/lithuanian-football-league-predictor/tour_eval_pred/run.py", line 146, in go
    all = pd.merge(df, df1, on=df['Winner'], how='inner')
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1088, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/orestas41/miniconda3/envs/mlflow-179e34a71618ccb1126551092a7decef1effd393/lib/python3.10/site-packages/pandas/core/generic.py", line 1848, in _get_label_or_level_values
    raise KeyError(key)
KeyError: index
1.685296    0.0
1.685290    0.5
1.685214    1.0
1.685207    0.0
1.685124    0.0
Name: Winner, dtype: float64